import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const poppins = Poppins({ subsets: ['latin'], weight: '300' });

export const metadata: Metadata = {
  title: 'Secret Santa',
  description: 'Generated by create next app',
  icons: {
    icon: '/santa.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <body className={cn('dark h-full overflow-hidden', poppins.className)}>
        {children}
      </body>
    </html>
  );
}
